#!/usr/bin/env bash
# GB-BRAIN — Remote Deploy Script
# ================================
# Usage: ./vps/deploy.sh ubuntu@1.2.3.4
#
# Rsyncs the project to /opt/gb-brain/ on the remote host,
# installs Python dependencies, and preserves an existing .env.
# Idempotent — safe to run multiple times.

set -e

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------

if [[ -z "$1" ]]; then
    echo "Usage: $0 <user@host>"
    echo "Example: $0 ubuntu@1.2.3.4"
    exit 1
fi

REMOTE="$1"
REMOTE_DIR="/opt/gb-brain"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "============================================="
echo "  GB-BRAIN Remote Deploy"
echo "  Target : ${REMOTE}:${REMOTE_DIR}"
echo "  Source : ${PROJECT_ROOT}"
echo "  Time   : $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo "============================================="

# ---------------------------------------------------------------------------
# Step 1: Ensure remote directory exists and is owned by the remote user
# ---------------------------------------------------------------------------

echo ""
echo "[1/4] Preparing remote directory …"
ssh "${REMOTE}" "sudo mkdir -p ${REMOTE_DIR} && \
    sudo chown -R \$(whoami):\$(whoami) ${REMOTE_DIR} && \
    echo '  Remote dir ready: ${REMOTE_DIR}'"

# ---------------------------------------------------------------------------
# Step 2: rsync project files
#         Excluded:
#           .env            — secrets, never overwrite
#           __pycache__/    — generated bytecode
#           .git/           — not needed on VPS
#           *.db            — SQLite databases are live data
#           data_cache/     — large local data cache
#           .DS_Store       — macOS metadata
#           *.pyc           — compiled bytecode
# ---------------------------------------------------------------------------

echo ""
echo "[2/4] Syncing project files (excluding secrets + caches) …"

rsync -avz --progress \
    --exclude='.env' \
    --exclude='__pycache__/' \
    --exclude='*.pyc' \
    --exclude='.git/' \
    --exclude='*.db' \
    --exclude='data_cache/' \
    --exclude='.DS_Store' \
    --exclude='*.egg-info/' \
    --exclude='.venv/' \
    --exclude='venv/' \
    --exclude='node_modules/' \
    --delete \
    "${PROJECT_ROOT}/" \
    "${REMOTE}:${REMOTE_DIR}/"

echo "  Rsync complete."

# ---------------------------------------------------------------------------
# Step 3: Install Python dependencies on remote
# ---------------------------------------------------------------------------

echo ""
echo "[3/4] Installing Python dependencies on remote …"

ssh "${REMOTE}" bash <<'REMOTE_SCRIPT'
set -e
REMOTE_DIR="/opt/gb-brain"
VENV_PYTHON="${REMOTE_DIR}/venv/bin/python"
VENV_PIP="${REMOTE_DIR}/venv/bin/pip"

# Create venv if it doesn't exist
if [[ ! -f "${VENV_PYTHON}" ]]; then
    echo "  Creating virtual environment …"
    python3.11 -m venv "${REMOTE_DIR}/venv"
fi

# Upgrade pip quietly then install requirements
echo "  Running pip install …"
"${VENV_PIP}" install --upgrade pip --quiet
"${VENV_PIP}" install -r "${REMOTE_DIR}/requirements.txt" --quiet

echo "  Dependencies installed."
REMOTE_SCRIPT

# ---------------------------------------------------------------------------
# Step 4: Preserve .env — only create from example if none exists
# ---------------------------------------------------------------------------

echo ""
echo "[4/4] Checking .env on remote …"

ssh "${REMOTE}" bash <<REMOTE_SCRIPT
set -e
REMOTE_DIR="${REMOTE_DIR}"

if test -f "\${REMOTE_DIR}/.env"; then
    echo "  .env already exists — NOT overwriting (secrets preserved)."
else
    if test -f "\${REMOTE_DIR}/.env.example"; then
        cp "\${REMOTE_DIR}/.env.example" "\${REMOTE_DIR}/.env"
        echo "  .env created from .env.example — FILL IN YOUR SECRETS:"
        echo "  nano \${REMOTE_DIR}/.env"
    else
        echo "  WARNING: No .env and no .env.example found."
        echo "  Create \${REMOTE_DIR}/.env manually before starting services."
    fi
fi

# Ensure data and log directories exist
mkdir -p "\${REMOTE_DIR}/data"
mkdir -p "\${REMOTE_DIR}/data/backups"
sudo mkdir -p /var/log/gb-brain
sudo chown -R \$(whoami):\$(whoami) /var/log/gb-brain
REMOTE_SCRIPT

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "============================================="
echo "  DEPLOY COMPLETE"
echo "  ${REMOTE}:${REMOTE_DIR}"
echo "============================================="
echo ""
echo "Next steps (if first deploy):"
echo "  ssh ${REMOTE}"
echo "  nano ${REMOTE_DIR}/.env            # fill in API keys"
echo "  ${REMOTE_DIR}/venv/bin/python scripts/init_db.py"
echo "  ${REMOTE_DIR}/venv/bin/python simulate/engine_parity_check.py"
echo "  sudo supervisorctl reread && sudo supervisorctl update"
echo ""
